# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: dist

jobs:
# Please do not rename this job
  build-project:
    name: build PinheiroTvServer
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          API_URL: "http://cvc123.com/get.php?username=xmq45874&password=qfw79423&type=m3u&output=ts"
          CI: true
          MONGO_URI: mongodb+srv://pinheiroprogramadorpython_db_user:sTeSPWhkryJ2XyXd@cluster0.nmp2mce.mongodb.net/PinheiroTvOnline?retryWrites=true&w=majority&appName=Cluster0
          SITE_URL: ${{ inputs.site-url }}
        run: npm start

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 1ba55ecc-24ba-4b4f-b130-b95532ac3e97
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/PinheiroTvServer/config.yaml
          action: upload
